photoAlbum/MvcPL/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Services;
using MvcPL.Infrastructure;
using MvcPL.Models;

namespace MvcPL.Controllers
{
    public class PhotosController : Controller
    {
        public const int ImagesOnPage = 6;
        public const int CommentOnPage = 3;

        private readonly IPhotoService photoService;
        private readonly IAccountService accountService;

        public PhotosController(IPhotoService photoService, IAccountService accountService)
        {
            this.photoService = photoService;
            this.accountService = accountService;
        }

        //Pagination
        public ActionResult Index(int page = 1)
        {
            PhotoPageInfo pageInfo = new PhotoPageInfo { PageNumber = page, PageSize = ImagesOnPage, Tag = string.Empty, 
                TotalItems = photoService.CountByTag(string.Empty) };
            IEnumerable<PhotoViewModel> photos = photoService.GetAll(0, ImagesOnPage*page)
                .Select(p=>p.ToPhotoViewModel());
            return View(new PaginationViewModel<PhotoViewModel> {PageInfo = pageInfo, Items = photos});
        }

        public ActionResult Find(string term)
        {
            IEnumerable<string> tags = photoService.FindTags(term);

            var projection = from t in tags
                select new
                {
                    label = t,
                    value = t
                };
            if (Request.IsAjaxRequest())
            {
                return Json(projection.ToList(), JsonRequestBehavior.AllowGet);
            }
            return View("Index");
        }

        public ActionResult Search(string tag = "", int page = 1)
        {
            PhotoPageInfo pageInfo = new PhotoPageInfo
            {
                PageNumber = page,
                PageSize = ImagesOnPage,
                Tag = tag,
                TotalItems = photoService.CountByTag(tag)
            };

            if (Request.IsAjaxRequest())
            {
                IEnumerable<PhotoViewModel> photos = photoService.GetByTag(tag, pageInfo.Skip, pageInfo.PageSize)
                    .Select(p => p.ToPhotoViewModel());

                PaginationViewModel<PhotoViewModel> pagedPhotos =
                    new PaginationViewModel<PhotoViewModel> { PageInfo = pageInfo, Items = photos };

                return Json(pagedPhotos, JsonRequestBehavior.AllowGet);
            }

            IEnumerable<PhotoViewModel> photos2 = photoService.GetByTag(tag, 0, ImagesOnPage*page)
                .Select(p => p.ToPhotoViewModel());

            PaginationViewModel<PhotoViewModel> pagedPhotos2 =
                new PaginationViewModel<PhotoViewModel> {PageInfo = pageInfo, Items = photos2};

            return View("Index", pagedPhotos2);
        }


        public ActionResult ShowImage(int id)
        {
            return File(photoService.GetById(id).Image, "image/jpeg");
        }

        public ActionResult PhotoDetails(int id)
        {
            PhotoDetailsViewModel photo = photoService.GetById(id).ToPhotoDetailsViewModel();
            photo.Owner = accountService.GetUserById(photo.UserId).ToPhotoOwnerViewModel();
            if (Request.IsAuthenticated)
            {
                photo.CurrentUserId = accountService.GetUserByLogin(User.Identity.Name).Id;
            }

            PageInfo pageInfo = new PageInfo
            {
                PageNumber = 1,
                PageSize = CommentOnPage,
                TotalItems = photoService.CountCommentByPhotoId(id)
            };
            IEnumerable<CommentViewModel> comments = photoService.GetCommentsByPhotoId(id, 0, CommentOnPage)
                .Select(p => p.ToCommentViewModel());

            ViewBag.Comments = new PaginationViewModel<CommentViewModel> {PageInfo = pageInfo, Items = comments};

            return PartialView("_PhotoDetails", photo);
        }

        [Authorize]
        public ActionResult LikePhoto(int photoId)
        {
            int userId = accountService.GetUserByLogin(User.Identity.Name).Id;
            photoService.LikePhoto(userId, photoId);
            PhotoRatingViewModel photo = photoService.GetById(photoId).ToPhotoRatingViewModel();
            return PartialView("_LikePhoto", photo);
        }

        [Authorize]
        public ActionResult DislikePhoto(int photoId)
        {
            int userId = accountService.GetUserByLogin(User.Identity.Name).Id;
            photoService.DislikePhoto(userId, photoId);
            PhotoRatingViewModel photo = photoService.GetById(photoId).ToPhotoRatingViewModel();
            return PartialView("_DislikePhoto", photo);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddComment(AddCommentViewModel model)
        {
            int userId = accountService.GetUserByLogin(User.Identity.Name).Id;
            photoService.AddComment(model.ToBllComment(userId, User.Identity.Name));
            return RedirectToAction("LoadMoreComment", new {page = 0, id = model.PhotoId});
        }

        public ActionResult LoadMoreComment(int page, int id)
        {
            PageInfo pageInfo = new PageInfo
            {
                PageNumber = page+1,
                PageSize = CommentOnPage,
                TotalItems = photoService.CountCommentByPhotoId(id)
            };
            IEnumerable<CommentViewModel> comments = photoService.GetCommentsByPhotoId(id, 
                pageInfo.Skip, pageInfo.PageSize).Select(p => p.ToCommentViewModel());

            var model = new PaginationViewModel<CommentViewModel> { PageInfo = pageInfo, Items = comments };
            return PartialView("_Comments", model);
        }

        [Authorize]
        public ActionResult DeletePhoto(int photoId)
        {
            photoService.Delete(photoId);
            return RedirectToAction("Index");
        }
    
    }
}

photoAlbum/MvcPL/Views/Shared/_FoundImages.cshtml
@using MvcPL.Models
@model PaginationViewModel<PhotoViewModel>

@*@if (Model.PageInfo.TotalItems == 0||(!Model.Items.Any()))
    {
        <div class="emptySearch">Sorry, there are no results for your search</div>
    }
    else

    {*@
@foreach (var p in Model.Items)
{
    <div id="image" class="col-lg-4 col-md-6">
        @*<a data-fancybox data-type="ajax" data-src="@Url.Action("PhotoDetails", new {p.Id})" href="javascript:;">*@
        <a href="@Url.Action("ShowImage", "Photos", new {p.Id})" data-type="image" data-fancybox="images">
            <img src="@Url.Action("ShowImage","Photos",  new {p.Id})" class="viewImage" />
        </a>

        <div>
            <a data-fancybox data-type="ajax" data-src="@Url.Action("PhotoDetails", "Photos", new {p.Id})"
               href="@Url.Action("PhotoDetails", "Photos", new {p.Id})" class="viewDetails">View Details</a>
        </div>

    </div>
}
@*}*@

photoAlbum/MvcPL/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/css")

    @*@Scripts.Render("~/bundles/modernizr")*@
</head>


<body>

    <header>
        <div class="container">
            <div class="logo">Photoalbum</div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
                @RenderSection("SearchForm", required: false)
            </nav>
        </div>
    </header>
    @RenderSection("profile", required: false)
    @RenderSection("body", required: false)

    @*<div class="container container-body">
            <div class="images" id="images">
                @RenderSection("body", required: false)
            </div>
            <div id="loadMore" class="loadMore">
                @RenderSection("loadMore", required: false)
            </div>
        </div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/search")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @RenderSection("scripts", required: false)

</body>
</html>

@*<script type="text/javascript">
        $(function () {
            var autocompleteUrl = '@Url.Action("Find", "Photos")';
            $("#tag").autocomplete({
                source: autocompleteUrl,
                minLength: 1,
                select: function (event, ui) {
                    onSelected(ui.item.label);
                }
            });
        });

        function onSelected(data) {
            $('#images').empty();
            var url = "@Url.Action("Search", "Photos")";
            var dataSend = {
                tag: data
            };
            $.post(
                url,
                dataSend,
                function (response) {
                    DisplayImages(response);
                });
        }

        function _arrayBufferToBase64(buffer) {
            var binary = '';
            var bytes = new Uint8Array(buffer);
            var len = bytes.byteLength;
            for (var i = 0; i < len; i++) {
                binary += String.fromCharCode(bytes[i]);
            }
            return window.btoa(binary);
        }

        function DisplayImages(data) {
            if (data.length == 0) {
                $('#images').prepend("<div class=\"emptySearch\">Sorry, there are no results for your search</div>");
            } else {
                $.each(data,
                    function (index, value) {
                        var imdiv = $('<div/>',
                            {
                                id: 'image',
                                class: 'col-lg-4 col-md-6 data-fancybox'
                            });
                        imdiv.append(
                        $('<img />').attr({
                            'src': "data:image/png;base64," + _arrayBufferToBase64(value.Image),
                            'height': '350px',
                            'width': 'auto'
                        })
                        ).appendTo('.images');
                    });
                $.each(data,
                    function (index, value) {
                        var imdiv = $('<div/>',
                            {
                                id: 'image',
                                class: 'col-lg-4 col-md-6'
                            });
                        imdiv.append(
                            $('<img />').attr({
                                'src': "data:image/png;base64," + _arrayBufferToBase64(value.Image),
                                'height': '350px',
                                'width': 'auto'
                            })
                        ).appendTo('.images');
                    });
                $.each(data,
                    function (index, value) {
                        var imdiv = $('<div/>',
                            {
                                id: 'image',
                                class: 'col-lg-4 col-md-6'
                            });
                        imdiv.append(
                            $('<img />').attr({
                                'src': "data:image/png;base64," + _arrayBufferToBase64(value.Image),
                                'height': '350px',
                                'width': 'auto'
                            })
                        ).appendTo('.images');
                    });

            }
        }




    </script>*@

photoAlbum/MvcPL/Views/Shared/_LoadMore.cshtml
@using MvcPL.Models
@model PaginationViewModel<PhotoViewModel>

@if (Model.PageInfo.TotalPages != Model.PageInfo.PageNumber)
{
    //string tag = ((PhotoPageInfo)Model.PageInfo).Tag;
    //int page = Model.PageInfo.PageNumber + 1;

    @*<a href="#" class="btn btn-outline-success my-2 my-sm-0" onclick="getPagedData('@tag', '@page')">Load more</a>
    @Html.RouteLink("Load more", new
       {
           controller = "Photos",
           action = "Search",
           tag = ((PhotoPageInfo)Model.PageInfo).Tag,
           page = Model.PageInfo.PageNumber + 1
       }, new
       {
           @class = "btn btn-outline-success my-2 my-sm-0",
           onclick = "GetPageData(" + ((PhotoPageInfo)Model.PageInfo).Tag + ", "(+Model.PageInfo.PageNumber + 1) + ")"
       });*@

    using (Html.BeginForm("Search", "Photos", new
    {
        tag = ((PhotoPageInfo)Model.PageInfo).Tag,
        page = Model.PageInfo.PageNumber + 1
    }, FormMethod.Post, new { @class = "", id = "loadMoreForm" }))
    {
        @Html.AntiForgeryToken()
        <button class="btn my-2 my-sm-0 signUpButton" id="buttonLoadMore" type="submit">Load more</button>
    }
}

photoAlbum/MvcPL/Views/Shared/_Profile_SignOut.cshtml
<div class="navbar-nav ml-auto mt-2 mt-lg-0" style="margin-right: 40px;">
    <a href="@Url.Action("Index", "Profile")">
        <img src="~/Content/user_green-5121.png" width="45px" height="40px" />
    </a>  
    <a href="@Url.Action("SignOut", "Account")">
        <img src="~/Content/signout.png" style="margin-left: 10px" width="45px" height="40px"/>
    </a>
</div>

photoAlbum/MvcPL/Views/Shared/_SearchForm.cshtml
@using System.Web.Mvc.Ajax
@*<form class="form-inline">
        <input class="form-control mr-sm-2" type="text" id="tag" placeholder="Search: #ballet" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>*@

@using (Html.BeginForm("Search", "Photos", FormMethod.Post, new { @class = "form-inline", id = "searchForm" }))
{
    @Html.AntiForgeryToken()
    @Html.TextBox("tag", "", new { @class = "form-control mr-sm-2", id = "tag", placeholder = "Search: #ballet" });
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
}

@if (Request.IsAuthenticated)
{
    @Html.Partial("_Profile_SignOut")
}
else
{
    <div class="navbar-nav ml-auto mt-2 mt-lg-0">

        @*<button class="btn ml-auto my-2 my-sm-0 signInButton" type="submit">Sign In</button>*@

        <a data-fancybox data-type="ajax" data-src="@Url.Action("SignIn", "Account")"
           href="@Url.Action("SignIn", "Account")" class="btn ml-auto my-2 my-sm-0 signInButton"
           type="submit">Sign In</a>

        <a data-fancybox data-type="ajax" data-src="@Url.Action("SignUp", "Account")"
           href="@Url.Action("SignUp", "Account")" class="btn ml-auto my-2 my-sm-0 signUpButton"
           type="submit">Sign Up</a>

        @*<button class="btn ml-auto my-2 my-sm-0 signUpButton" type="submit">Sign Up</button>*@
    </div>
}

photoAlbum/MvcPL/Views/Shared/_SearchFormAuthRedirectToHome.cshtml
@using System.Web.Mvc.Ajax
@*<form class="form-inline">
        <input class="form-control mr-sm-2" type="text" id="tag" placeholder="Search: #ballet" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>*@

@using (Html.BeginForm("Search", "Photos", FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.AntiForgeryToken()
    @Html.TextBox("tag", "", new { @class = "form-control mr-sm-2", placeholder = "Search: #ballet" });
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
}


    <div class="navbar-nav ml-auto mt-2 mt-lg-0">

        <a href="@Url.Action("Index", "Photos")">
            <img src="~/Content/home.png" width="45px" height="40px" />
        </a>
        
        <a href="@Url.Action("Index", "Profile")">
            <img src="~/Content/user_green-5121.png" style="margin-left: 10px" width="45px" height="40px" />
        </a> 

        <a href="@Url.Action("SignOut", "Account")">
            <img src="~/Content/signout.png" style="margin-left: 10px" width="45px" height="40px"/>
        </a>

    </div>